### ISSUE TITLE
Testing clean clone of the repo segfaults

### ISSUE THREAD

**Issue by nicmr** [Altemista/housekeeping#12]
## Description
When cloning the repository and trying to run the tests, the program segfaults when testing pkg/gitlab.

## Steps to reproduce:
```
git clone https://github.com/altemista/housekeeping
cd housekeeping
go test ./...
```
## Output
```
?   	github.com/Altemista/housekeeping	[no test files]
--- FAIL: TestGitlabServiceMakeAPICall (105.48s)
    gitlab_test.go:48: Get https://gitlab.kubermatic.lab.altemista.cloud/api/v4/version: EOF
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7fd21b]

goroutine 5 [running]:
testing.tRunner.func1(0xc0000dc500)
	/usr/local/go/src/testing/testing.go:830 +0x388
panic(0x86d8e0, 0xc8c1d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/Altemista/housekeeping/pkg/gitlab.TestGitlabServiceMakeAPICall(0xc0000dc500)
	/home/nico/Code/Altemista/housekeeping/pkg/gitlab/gitlab_test.go:50 +0x16b
testing.tRunner(0xc0000dc500, 0x8fa220)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x357
FAIL	github.com/Altemista/housekeeping/pkg/gitlab	105.486s
ok  	github.com/Altemista/housekeeping/pkg/housekeeping	0.011s
2019/07/23 16:56:52 Error: Both mail.verifiedsenderinaws and mail.fixedrecipient must be provided.
FAIL	github.com/Altemista/housekeeping/pkg/mail	0.004s
2019/07/23 16:56:54 Error: store.bucket must be provided.
FAIL	github.com/Altemista/housekeeping/pkg/store	0.004s
```

## Expected behaviour
Output errors similar to those in /pkg/mail and pkg/store, indicating that certain variables have to be provided.
Segfaulting from a nil pointer deref should be prevented through `!= nil` checks where applicable.

**Comment by markushinz** [comment]
Cannot reproduce, I get errors that the config file is missing (as intended):

```
?       github.com/Altemista/housekeeping       [no test files]
2019/08/05 10:25:45 Error - Could not read config file:Config File "config" Not Found in "[/home/hinzma/git/housekeeping]"
FAIL    github.com/Altemista/housekeeping/pkg/gitlab    0.003s
ok      github.com/Altemista/housekeeping/pkg/housekeeping      0.011s
2019/08/05 10:25:47 Error - Could not read config file:Config File "config" Not Found in "[/home/hinzma/git/housekeeping]"
FAIL    github.com/Altemista/housekeeping/pkg/mail      0.004s
2019/08/05 10:25:49 Error - Could not read config file:Config File "config" Not Found in "[/home/hinzma/git/housekeeping]"
FAIL    github.com/Altemista/housekeeping/pkg/store     0.004s
```

Also, if the file existed, gitlab_test.go implements the following check:

```
if !(viper.IsSet("gitlab.host") && viper.IsSet("gitlab.token")) {
		log.Fatal("Error: Not all required parameters werde provided.")
	}
```

**Comment by nicmr** [comment]
You're right, I can't reproduce it anymore either. Maybe some of your changes had already fixed it in the meantime 😄 

Let's close this issue.
